In [3]:
import pandas as pd

gdp = pd.read_csv('../data/raw/gdp-per-capita-maddison-project-database/gdp-per-capita-maddison-project-database.csv')
life_expentancy = pd.read_csv('../data/raw/life-expectancy-hmd-unwpp/life-expectancy-hmd-unwpp.csv')
calories = pd.read_csv('../data/raw/daily-per-capita-caloric-supply/daily-per-capita-caloric-supply.csv')
vegetables = pd.read_csv('../data/raw/vegetable-consumption-per-capita/vegetable-consumption-per-capita.csv')
income_groups = pd.read_csv('../data/raw/world-bank-income-groups/world-bank-income-groups.csv')

In [10]:
gdp.head()

        Entity Code  Year  GDP per capita GDP per capita (Annotations)
0  Afghanistan  AFG  1950          1156.0                          NaN
1  Afghanistan  AFG  1951          1170.0                          NaN
2  Afghanistan  AFG  1952          1189.0                          NaN
3  Afghanistan  AFG  1953          1240.0                          NaN
4  Afghanistan  AFG  1954          1245.0                          NaN

In [6]:
life_expentancy.head()

        Entity Code  Year  Life expectancy at birth, totals, period
0  Afghanistan  AFG  1950                                   28.1563
1  Afghanistan  AFG  1951                                   28.5836
2  Afghanistan  AFG  1952                                   29.0138
3  Afghanistan  AFG  1953                                   29.4521
4  Afghanistan  AFG  1954                                   29.6975

In [7]:
calories.head()

        Entity Code  Year  Daily calorie supply per person
0  Afghanistan  AFG  1961                        2914.3484
1  Afghanistan  AFG  1962                        2835.6074
2  Afghanistan  AFG  1963                        2623.7017
3  Afghanistan  AFG  1964                        2872.5679
4  Afghanistan  AFG  1965                        2876.1790

In [8]:
vegetables.head()

        Entity Code  Year  Vegetable supply per person
0  Afghanistan  AFG  1961                    35.712673
1  Afghanistan  AFG  1962                    36.424480
2  Afghanistan  AFG  1963                    37.799587
3  Afghanistan  AFG  1964                    39.075870
4  Afghanistan  AFG  1965                    39.727467

In [9]:
income_groups.head()

        Entity Code  Year World Bank's income classification
0  Afghanistan  AFG  1987               Low-income countries
1  Afghanistan  AFG  1988               Low-income countries
2  Afghanistan  AFG  1989               Low-income countries
3  Afghanistan  AFG  1990               Low-income countries
4  Afghanistan  AFG  1991               Low-income countries

In [16]:
df = gdp.merge(life_expentancy, on=["Entity", "Code", "Year"], how="inner")
df = df.merge(calories, on=["Entity", "Code", "Year"], how="inner")
df = df.merge(vegetables, on=["Entity", "Code", "Year"], how="inner")
df = df.merge(income_groups, on=["Entity", "Code", "Year"], how="inner")

In [17]:
df.describe()

,Year,GDP per capita,"Life expectancy at birth, totals, period",Daily calorie supply per person,Vegetable supply per person
count,5382.000000,5382.000000,5382.000000,5382.000000,5382.000000
mean,2005.175771,13735.456803,68.408182,2746.806197,89.379571
std,10.212040,14995.294798,9.830472,525.949554,65.322453
min,1987.000000,377.580080,12.157500,1386.576700,4.369483
25%,1996.000000,2724.447075,61.722575,2312.962250,37.108694
50%,2005.000000,8101.398000,70.670400,2741.978050,72.841412
75%,2014.000000,19687.476750,75.986550,3166.244850,126.189816
max,2022.000000,150732.220000,85.263200,4393.150400,423.040440

In [18]:
df["Entity"].unique()

<StringArray>
[         'Afghanistan',              'Albania',              'Algeria',
               'Angola',            'Argentina',              'Armenia',
            'Australia',              'Austria',           'Azerbaijan',
              'Bahrain',
 ...
 'United Arab Emirates',       'United Kingdom',        'United States',
              'Uruguay',           'Uzbekistan',            'Venezuela',
              'Vietnam',                'Yemen',               'Zambia',
             'Zimbabwe']
Length: 161, dtype: str